-- TANA V10: usuarios + actividad persistente separada
create table if not exists public.tana_users (
  email text primary key,
  role text not null default 'Estudiante',
  first_seen timestamptz not null,
  last_seen timestamptz not null,
  visits integer not null default 0
);

create table if not exists public.tana_activity (
  id bigint generated by default as identity primary key,
  email text not null references public.tana_users(email) on delete cascade,
  timestamp timestamptz not null default now(),
  event text not null,
  detail text not null default '',
  signature text not null default ''
);

create index if not exists tana_activity_email_timestamp_idx
  on public.tana_activity (email, timestamp desc);

-- El servidor de TANA usa la clave secreta de Supabase.
-- Se puede mantener RLS activado sin políticas públicas porque la clave secreta
-- del servidor tiene privilegios suficientes y no se expone al navegador.
alter table public.tana_users enable row level security;
alter table public.tana_activity enable row level security;
